gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is POBOY.\p"
	.string "And somehow they let me become\n"
	.string "a POKéMON PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "At times as friendly playmates, and\l"
	.string "at times as collaborative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "Some people milk them for CONTENT,\n"
	.string "taking advantage of the lack of a\l"
	.string "POKéMON labor union. Weirdge.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "To unravel those POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "This is where I'm supposed\n"
	.string "to ask about your gender…\p"
	.string "but all it says here is\n"
	.string "“breeder.”$"

gText_Birch_BoyOrGirl::
	.string "It says here you're a boy.\n"
	.string "Is that right?$"

gText_Birch_WhatsYourName::
	.string "Remind me,\n"
	.string "who are you again?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're the {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of AUST- I mean LITTLEROOT.\l"
	.string "POGGERS!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "friends, and viewership await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
